import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";
import "jspdf-autotable";
import { Separator } from "@/components/ui/separator";

export default function IncomeInvoicesModel({ open, onClose, income }) {
	const handleDownload = () => {
		const doc = new jsPDF();

		doc.setFont("helvetica", "bold");
		doc.setFontSize(22);
		doc.setTextColor(40);
		doc.text("Event Invoice", 105, 20, { align: "center" });

		doc.setFont("helvetica", "normal");
		doc.setFontSize(12);
		doc.setTextColor(100);
		doc.text("Generated by XYZ Maintenance System", 105, 28, {
			align: "center",
		});

		doc.setDrawColor(200);
		doc.line(10, 32, 200, 32);

		const columns = ["Field", "Value"];
		const rows = [
			["Invoice ID", income.invoiceId],
			["Owner Name", income.ownerName],
			["Bill Date", income.billDate],
			["Payment Date", income.paymentDate],
			["Next Event Date", income.nextEventDate],
			["Phone Number", income.phoneNumber],
			["Email", income.email],
			["Event Name", income.eventName],
			["Description", income.description],
			["Event Amount", `₹${income.eventAmount}`],
			["Members", income.members],
			[
				"Grand Total",
				`₹${(income.members * parseFloat(income.eventAmount)).toFixed(
					2
				)}`,
			],
			["Note", income.note || "No additional notes provided"],
		];

		doc.autoTable({
			head: [columns],
			body: rows,
			startY: 40,
			theme: "grid",
			styles: {
				fontSize: 12,
				cellPadding: 5,
				lineColor: [200, 200, 200],
				lineWidth: 0.1,
			},
			headStyles: {
				fillColor: [34, 112, 147],
				textColor: [255, 255, 255],
				fontSize: 12,
				fontStyle: "bold",
			},
			bodyStyles: {
				textColor: [40, 40, 40],
			},
			alternateRowStyles: {
				fillColor: [240, 248, 255],
			},
		});

		const pageHeight = doc.internal.pageSize.height;
		doc.setFont("helvetica", "italic");
		doc.setFontSize(10);
		doc.setTextColor(120);
		doc.text(
			`Generated on: ${new Date().toLocaleDateString()} | Invoice ID: ${
				income.invoiceId
			}`,
			10,
			pageHeight - 10
		);
		doc.text("Thank you for your payment!", 200, pageHeight - 10, {
			align: "right",
		});

		doc.save(`Event_Invoice_${income.invoiceId}.pdf`);
	};

	return (
		<Dialog open={open} onOpenChange={onClose}>
			<DialogContent className="w-[300px] md:w-full p-3 md:p-6 bg-white rounded-lg shadow-lg">
				<DialogHeader >
					<DialogTitle className="text-xl text-start md:text-start font-bold text-gray-800 mb-1 md:mb-3">
						Event Invoice 
					</DialogTitle>
					<Separator />
					<DialogDescription className="space-y-10">
						<div className="grid grid-cols-2 gap-x-6 gap-y-4 mt-5">
							<div>
								<p className="text-sm text-gray-500 text-start">
									Invoice ID
								</p>
								<p className="font-medium text-sm md:text-[16px] text-gray-800 text-start">
									{income.invoiceId}
								</p>
							</div>
							<div>
								<p className="text-sm text-gray-500 text-start">
									Owner Name
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.ownerName}
								</p>
							</div>
							<div>
								<p className="text-sm text-gray-500 text-start">
									Bill Date
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.billDate}
								</p>
							</div>
							<div>
								<p className="text-sm text-gray-500 text-start">
									Payment Date
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.paymentDate}
								</p>
							</div>
							<div>
								<p className="text-sm text-gray-500 text-start">
									Next Event Date
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.nextEventDate}
								</p>
							</div>
							<div>
								<p className="text-sm text-gray-500 text-start">
									Phone Number
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.phoneNumber}
								</p>
							</div>
							<div>
								<p className="text-sm text-gray-500 text-start">Email</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.email}
								</p>
							</div>
							<div className="col-span-2">
								<p className="text-sm text-gray-500 text-start">
									Event Name
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.eventName}
								</p>
							</div>
							<div className="col-span-2">
								<p className="text-sm text-start text-gray-500">
									Description
								</p>
								<p className="text-base text-start font-medium text-gray-800">
									{income.description}
								</p>
							</div>
							<div className="col-span-2">
								<p className="text-sm text-gray-500 text-start">
									Event Amount
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									₹{income.eventAmount}
								</p>
							</div>
							<div className="col-span-2">
								<p className="text-sm text-gray-500 text-start">Members</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.members}
								</p>
							</div>
							<div className="col-span-2">
								<p className="text-sm text-gray-500 text-start">
									Grand Total
								</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									₹{" "}
									{(
										income.members *
										parseFloat(income.eventAmount)
									).toFixed(2)}
								</p>
							</div>
							<div className="col-span-2">
								<p className="text-sm text-gray-500 text-start">Note</p>
								<p className="text-sm md:text-[16px] font-medium text-gray-800 text-start">
									{income.note ||
										"No additional notes provided."}
								</p>
							</div>
						</div>

						<div>
							<Button
								onClick={handleDownload}
								className="w-full py-3 rounded-lg font-medium shadow-md bg-blue-500 text-white hover:bg-blue-600"
							>
								Download Invoice
							</Button>
						</div>
					</DialogDescription>
				</DialogHeader>
			</DialogContent>
		</Dialog>
	);
}
