export const noteData = [
	{
		id: 1,
		title: "Meeting with Residents",
		description:
			"Discussed budget allocation for maintenance. The residents expressed concerns about the current maintenance budget and suggested reallocating funds to address more pressing issues such as plumbing and electrical repairs.",
	},
	{
		id: 2,
		title: "Security Inspection",
		description:
			"Conducted a security check and noted issues for review. Found several security cameras not functioning properly and recommended immediate replacement. Also, discussed the need for additional lighting in the parking areas.",
	},
	{
		id: 3,
		title: "Community Event Planning",
		description:
			"Met with the event planning committee to discuss the upcoming community event. Decided on a theme and outlined the necessary preparations, including venue setup, catering, and entertainment.",
	},
	{
		id: 4,
		title: "Financial Report Review",
		description:
			"Reviewed the quarterly financial report. Noted a significant increase in utility costs and recommended exploring alternative energy providers to reduce expenses.",
	},
	{
		id: 5,
		title: "Maintenance Request Follow-Up",
		description:
			"Followed up on several maintenance requests submitted by residents. Assigned tasks to the maintenance team and scheduled completion dates. Noted that some requests were more urgent than others and prioritized accordingly.",
	},
	{
		id: 6,
		title: "New Resident Orientation",
		description:
			"Conducted an orientation session for new residents. Provided an overview of community rules, amenities, and services. Also, introduced them to key contacts such as the property manager and security personnel.",
	},
	{
		id: 7,
		title: "Emergency Preparedness Meeting",
		description:
			"Held a meeting to discuss emergency preparedness plans. Reviewed the current emergency response procedures and identified areas for improvement. Discussed the importance of regular drills and communication strategies.",
	},
	{
		id: 8,
		title: "Complaint Resolution",
		description:
			"Resolved a complaint from a resident regarding noise disturbances. Addressed the issue by speaking with the neighbors involved and setting up a mediation session to ensure a peaceful resolution.",
	},
	{
		id: 9,
		title: "Landscaping Update",
		description:
			"Met with the landscaping team to discuss the upcoming season's plans. Reviewed the current state of the grounds and identified areas that need attention. Planned for new plantings and scheduled maintenance tasks.",
	},
	{
		id: 10,
		title: "Vendor Contract Renewal",
		description:
			"Reviewed and renewed contracts with key vendors. Negotiated better terms and pricing for services such as waste management, pest control, and landscaping. Ensured that all contracts are up-to-date and compliant with community standards.",
	},
];
